const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS'
const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
const SET_SELECTED_SUBCATEGORY = 'SET_SELECTED_SUBCATEGORY'

export {
    SET_ALL_PRODUCTS,
    SET_SELECTED_CATEGORY,
    SET_SELECTED_SUBCATEGORY
}